//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrchestratorApplication.Models.JobsModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public string Process { get; set; }
        public string Robot { get; set; }
        public string Environment { get; set; }
        public string State { get; set; }
        public string Started { get; set; }
        public string Ended { get; set; }
        public string Source { get; set; }
    }
}
