//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrchestratorApplication.Models.MonitoringModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonitoringRuntime
    {
        public string Machine { get; set; }
        public string Total { get; set; }
        public string Exe { get; set; }
    }
}
