//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrchestratorApplication.Models.MonitoringModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RobotDetail
    {
        public string Name { get; set; }
        public string Environment { get; set; }
        public string Type { get; set; }
        public string Machine { get; set; }
        public string Status { get; set; }
        public string Current_process { get; set; }
        public string Queue { get; set; }
    }
}
